config/routes.rb
Rails.application.routes.draw do
  get 'plans/index'
  get 'plans/show'
  get 'plans/new'
  get 'plans/edit'
  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete '/logout', to:'sessions#destroy'
    resources :users


  root to: 'users#index'
  resources :users
end
# For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/plan.rb
class Plan < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password

  validates :name, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  helper_method :current_user
  before_action :login_required

  private

  def current_user
    @current_user ||= User.find_by(id: sesion[:user_id]) if session[:user_id]
  end

  def login_required
    redirect_to login_url unless current_user
  end
end

app/controllers/plans_controller.rb
class PlansController < ApplicationController
  def index
  end

  def show
  end

  def new
  end

  def edit
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  skip_before_action :login_required
  def new
  end

  def create
    user = User.find_by(name: session_params[:name])

    if user&.authenticate(session_params[:password])
      session[:user_id] = user.id
      redirect_to root_url, notice: 'ログインしました。'
    else
      render :new
    end
  end

  def destroy
    redirect_to root_url, notice: 'ログアウトしました。'
  end


 private

  def session_params
    params.require(:session).permit(:name, :password)
  end
end

app/controllers/users_controller.rb
 class UsersController < ApplicationController
   def index
   end

   def show
   end

   def new
     @user = User.new
   end

   def edit
   end

   def create
     @user = User.new(user_params)

     if @user.save
       redirect_to user_url(@user), notice: "ユーザー「#{@user.name}」を登録しました。"
     else
       render :new
   end
 end

 private

 def user_params
   params.require(:user).permit(:name, :password, :password_confirmation)
 end
end

app/helpers/admin/users_helper.rb
module Admin::UsersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/plans_helper.rb
module PlansHelper
end

app/helpers/session_helper.rb
module SessionHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.slim
doctype html
html
  head
    title
      | Moneymanagement
    = csrf_meta_tags
    = csp_meta_tag
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
  body
    .app-title.navbar.navbar-expand-md.navbar-light.bg-light
      .navbar-brand Stocker

      ul.navbar-nav.ml-auto
      - if current_user
        li.nav-item= link_to 'ユーザー登録', users_path, class: 'nav-link'
        li.nav-item= link_to 'ログアウト', logout_path, method: :delete, class: 'nav-link'
      - else
        li.nav-item= link_to 'ログイン', login_path, class: 'nav-link'
    .container
     - if flash.notice.present?
       .alert.alert-succes= flash.notice
     = yield

app/views/plans/edit.html.slim
h1 Plans#edit
p Find me in app/views/plans/edit.html.slim

app/views/plans/index.html.slim
h1 Plans#index
p Find me in app/views/plans/index.html.slim

app/views/plans/new.html.slim
h1 Plans#new
p Find me in app/views/plans/new.html.slim

app/views/plans/show.html.slim
h1 Plans#show
p Find me in app/views/plans/show.html.slim

app/views/users/edit.html.slim
h1 Users#edit
p Find me in app/views/users/edit.html.slim

app/views/users/index.html.slim
h1 Users#index
h1 stocker
= link_to '新規登録', new_user_path, class:'btn btn-primary'

app/views/users/new.html.slim
h1 ユーザーの登録/編集

.nav.justify-content-end
  = link_to 'ホーム', users_path, class: 'nav-link'

= form_with model: @user, local: true do |f|
  .form-group
    = f.label :name, 'ユーザー名'
    = f.text_field :name, class: 'form-control', id: 'user_name'
  .form-group
    = f.label :password, 'パスワード'
    = f.password_field :password, class: 'form-control', minlength: "8", maxlength: "16"
  .form-group
    = f.label :password_confirmation, 'パスワード(確認)'
    = f.password_field :password, class: 'form-control', minlength: "8", maxlength: "16"
  = f.submit '登録', class: 'btn btn-primary'

app/views/users/show.html.slim
h1 Users#show
p Find me in app/views/users/show.html.slim